version: '3.8'

services:
  verdaccio:
    image: verdaccio/verdaccio:latest
    container_name: verdaccio
    restart: unless-stopped
    ports:
      - "4873:4873"
    volumes:
      - ./config/config-base.yaml:/verdaccio/conf/config.yaml
      # - ./config/config-routed.yaml:/verdaccio/conf/config.yaml
      - ./storage:/verdaccio/storage 
    environment:
      - VERDACCIO_APPDIR=/verdaccio
    networks:
      - default

networks:
  default:
    name: verdaccio-default