uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    cache: true # Enable caching for npm packages

packages:
  "**":
    access: $anonymous
    publish: $anonymous
    proxy: npmjs # Default to npmjs uplink for all packages

auth:
  htpasswd:
    file: /verdaccio/conf/htpasswd
    max_users: -1 # Disable user limits, optional

middlewares:
  audit:
    enabled: true

logs:
  - { type: stdout, format: pretty, level: http }
